version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql

  postgres-test:
    image: postgres
    ports:
      - '5433:5433'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data_test'
      - ./database-setup.sql:/docker-entrypoint-initdb.d/database-setup.sql

volumes:
  postgres:
  